pipeline{
    agent any 

    tools {
        python 'Python3'
    }

    environment {
        PIPENV_VENV_IN_PROJECT = '1'
        DOCKER_IMAGE = 'bixoloo/messaging-app'
        DOCKER_CREDENTIALS = credentials('docker-hub-credentials')
        DOCKER_USER = credentials('docker-user')
        DOCKER_PASSWORD = credentials('docker-password')


    }

    stages {
        stage('Clone Repor'){
            steps {
                git credentialsId: 'github-creds', url:  'git@github.com:bicosteve/alx-backend-python.git'
            }
        }

        stage('Install Pipenv'){
            steps {
                sh 'pip install --upgrade pip pipenv'
            }
        }

        stage('Install Dependancies'){
            steps {
                // Loads env vars and install packages
                sh '''
                export $(grep -v "^#" .env | xargs) && pipenv install --dev
                '''
            }
        }

        stage('Run Tests'){
            steps {
                sh 'pipenv run pytest --junitxml=report.xml'
            }
        }

        stage('Publish Report'){
            steps {
                junit 'report.xml'
            }
        }

        stage('Build docker image'){
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$BUILD_NUMBER .'
            }
        }

        stage('Push to Docker Hub'){
            steps {
                withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS, usernameVariable: $DOCKER_USER, passwordVariable: $DOCKER_PASSWORD)]){
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u \"$DOCKER_USER" --password-stdin
                        docker push $DOCKER_IMAGe:$BUILD_NUMBER
                        docker tag $DOCKER_IMAGE:$BUILD_NUMBER \$DOCKER_IMAGE:latest
                        docker push $DOCKER_IMAGE:latest
                    '''
                }
            }
        }


    }
}